### ISSUE TITLE
Latest Git version installation fails on Windows

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/ibm-cloud-developer-tools#152]
There is no more Git 2.24.1.1 file to download in https://github.com/git-for-windows/git/releases

It has been changed to 2.24.1.2 :( so the following code fails:

https://github.com/IBM-Cloud/ibm-cloud-developer-tools/blob/1140fa8a8f5f07e3ce8d808bc9341cd2f0d7d987/windows-installer/idt-win-installer.ps1#L138

The correct filename today should be: `https://github.com/git-for-windows/git/releases/download/v$gitVersion.windows.2/Git-$gitVersion.2-64-bit.exe`

**Comment by chiunglee** [comment]
This fix seems to have only worked for Git 2.24.1(2) specifically. Now that the current Git version is at 2.26.0 (and for most of the versions after 2.24.1), the current filename needs to have `windows.1` instead of `windows.2`.

A best solution would be to add a check to see if the current version requires the `windows.X` to change.
